from google import genai
import os
from dotenv import load_dotenv
from typing import Annotated, List, Literal, Optional
import json
from datetime import datetime
from fastapi import FastAPI, Request, File, UploadFile, Form
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware

load_dotenv()

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Use specific domain in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

Client = genai.Client(api_key=GEMINI_API_KEY)

application_name = "note_taking_app"

@app.post("/chat-with-ai")
async def chat_with_ai(request:Request):
    """
    Endpoint to handle chat interactions with the AI model. 
    This endpoint receives a JSON payload containing the user's message and the conversation history, and it returns a response generated by the AI model.
    User chats about a specific lecture.
    Gemini will have the final_summary of the lecture, and the user can ask questions about it. The AI will respond based on the final_summary and any additional context provided in the conversation history.
    Gemini will make sure to answer on the basis of the final summary
    Frontend will create a list saving the conversation history, and send it to the backend with every new message. The backend will send the entire conversation history to Gemini, so it can answer in context.
    
    Will try to make sure the history is not too long.

    Args:
        request (Request): The incoming HTTP request containing the JSON payload with the user's message and conversation history.

    Returns:
           JSONResponse: A JSON response containing the AI model's generated response to the user's message. The response will be based on the final summary of the lecture and any additional context provided in the conversation history.

    Raises:
        Exception: If there is an error during the AI model interaction, an error message is returned in the JSON response.               

    """

    data = await request.json()
    user_message = data.get("user_message")
    conversation_history = data.get("conversation_history", [])
    final_summary = data.get("final_summary")

    # Construct the prompt for the AI model
    prompt = f"Final Summary: {final_summary}\n\nConversation History: {conversation_history}\n\nUser Message: {user_message}\n\nPlease respond based on the final summary and the context provided."

    try:
        # Call the Gemini AI model to generate a response
        response = Client.responses.create(
            model="gemini-1.5",
            input=prompt,
            application=application_name
        )

        ai_response = response.output_text

        return JSONResponse(content={"ai_response": ai_response})

    except Exception as e:
        return JSONResponse(content={"error": str(e)}, status_code=500)

 
    